# Generated by Django 4.2.4 on 2023-11-09 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('visiting_place_name', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposits', models.IntegerField()),
                ('Remaining_amount', models.IntegerField()),
                ('completed_payment_payment', models.IntegerField()),
                ('traveldestination', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accomodation', models.TextField(blank=True, null=True)),
                ('Game_drive', models.CharField(blank=True, max_length=5, null=True)),
                ('any_other_services', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travellers_number', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('remaining_money', models.IntegerField()),
                ('complete_payment', models.IntegerField()),
                ('travelling_time', models.DateField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='savetotravel.hoteldestination')),
            ],
        ),
        migrations.AddField(
            model_name='hoteldestination',
            name='service',
            field=models.ManyToManyField(to='savetotravel.services'),
        ),
    ]
