# Generated by Django 4.2.4 on 2023-11-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savetotravel', '0001_initial'),
    ]

    operations = [
    ]
