# Generated by Django 4.2.4 on 2023-11-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savetotravel', '0003_remove_hoteldestination_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldestination',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
