# Generated by Django 4.2.5 on 2023-11-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savetotravel', '0004_hoteldestination_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldestination',
            name='service',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.RemoveField(
            model_name='user_destination',
            name='destination',
        ),
        migrations.DeleteModel(
            name='HotelDestination',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='User_destination',
        ),
    ]
