# Generated by Django 4.2.5 on 2023-11-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savetotravel', '0005_remove_hoteldestination_service_delete_payments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=50, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
