# Generated by Django 4.2.5 on 2023-11-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savetotravel', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked_events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Hotel_name', models.CharField(max_length=50)),
                ('Contact', models.BigIntegerField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('images', models.ImageField(upload_to='images/')),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('id_no', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
