# Generated by Django 4.2.5 on 2023-11-28 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savetotravel', '0007_booked_events_hotel_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_events',
            name='Payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savetotravel.payments'),
        ),
        migrations.AddField(
            model_name='booked_events',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savetotravel.events'),
        ),
        migrations.AddField(
            model_name='booked_events',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savetotravel.user'),
        ),
        migrations.AddField(
            model_name='events',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savetotravel.hotel'),
        ),
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savetotravel.user'),
        ),
        migrations.AddField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savetotravel.user'),
        ),
    ]
